[package]
name = "grenad"
version = "0.1.0"
authors = ["Clément Renault <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
flate2 = { version = "1.0", optional = true }
log = "0.4.11"
memmap = "0.7.0"
snap = { version = "1.0.0", optional = true }
tempfile = "3.1.0"
zstd = { version = "0.5.1", optional = true }

[dev-dependencies]
quickcheck = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.19.0"

[features]
default = ["zlib", "snappy", "zstd"]
snappy = ["snap"]
zlib = ["flate2"]
