[package]
name = "ssst"
version = "0.1.0"
authors = ["Clément Renault <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
flate2 = { version = "1.0", optional = true }
log = "0.4.11"
nix = { version = "0.19.0", optional = true }
snap = { version = "1.0.0", optional = true }
tempfile = "3.1.0"
zstd = { version = "0.5.1", optional = true }

[dev-dependencies]
quickcheck = "0.9"

[features]
default = ["zlib", "snappy", "zstd"]
file-fuse = ["nix"]
snappy = ["snap"]
zlib = ["flate2"]
